/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolRouteImport } from './routes/_school'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolIndexRouteImport } from './routes/_school/index'
import { Route as SchoolAccountRouteImport } from './routes/_school/account'
import { Route as SchoolApprovalsRouteImport } from './routes/_school/approvals'
import { Route as SchoolAssignmentsRouteImport } from './routes/_school/assignments'
import { Route as SchoolAttendanceRouteImport } from './routes/_school/attendance'
import { Route as SchoolCalendarRouteImport } from './routes/_school/calendar'
import { Route as SchoolGroupsRouteImport } from './routes/_school/groups'
import { Route as SchoolMessagesRouteImport } from './routes/_school/messages'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SchoolRoute = SchoolRouteImport.update({
  id: '/_school',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolAccountRoute = SchoolAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolApprovalsRoute = SchoolApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolAssignmentsRoute = SchoolAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolAttendanceRoute = SchoolAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolCalendarRoute = SchoolCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolGroupsRoute = SchoolGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolMessagesRoute = SchoolMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SchoolRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SchoolIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/account': typeof SchoolAccountRoute
  '/approvals': typeof SchoolApprovalsRoute
  '/assignments': typeof SchoolAssignmentsRoute
  '/attendance': typeof SchoolAttendanceRoute
  '/calendar': typeof SchoolCalendarRoute
  '/groups': typeof SchoolGroupsRoute
  '/messages': typeof SchoolMessagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/account': typeof SchoolAccountRoute
  '/approvals': typeof SchoolApprovalsRoute
  '/assignments': typeof SchoolAssignmentsRoute
  '/attendance': typeof SchoolAttendanceRoute
  '/calendar': typeof SchoolCalendarRoute
  '/groups': typeof SchoolGroupsRoute
  '/messages': typeof SchoolMessagesRoute
  '/': typeof SchoolIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_school': typeof SchoolRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/_school/account': typeof SchoolAccountRoute
  '/_school/approvals': typeof SchoolApprovalsRoute
  '/_school/assignments': typeof SchoolAssignmentsRoute
  '/_school/attendance': typeof SchoolAttendanceRoute
  '/_school/calendar': typeof SchoolCalendarRoute
  '/_school/groups': typeof SchoolGroupsRoute
  '/_school/messages': typeof SchoolMessagesRoute
  '/_school/': typeof SchoolIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/account'
    | '/approvals'
    | '/assignments'
    | '/attendance'
    | '/calendar'
    | '/groups'
    | '/messages'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy'
    | '/signup'
    | '/account'
    | '/approvals'
    | '/assignments'
    | '/attendance'
    | '/calendar'
    | '/groups'
    | '/messages'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_school'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/_school/account'
    | '/_school/approvals'
    | '/_school/assignments'
    | '/_school/attendance'
    | '/_school/calendar'
    | '/_school/groups'
    | '/_school/messages'
    | '/_school/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SchoolRoute: typeof SchoolRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_school': {
      id: '/_school'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school/': {
      id: '/_school/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/account': {
      id: '/_school/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SchoolAccountRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/approvals': {
      id: '/_school/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof SchoolApprovalsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/assignments': {
      id: '/_school/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof SchoolAssignmentsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/attendance': {
      id: '/_school/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof SchoolAttendanceRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/calendar': {
      id: '/_school/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof SchoolCalendarRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/groups': {
      id: '/_school/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof SchoolGroupsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/messages': {
      id: '/_school/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof SchoolMessagesRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SchoolRouteChildren {
  SchoolAccountRoute: typeof SchoolAccountRoute
  SchoolApprovalsRoute: typeof SchoolApprovalsRoute
  SchoolAssignmentsRoute: typeof SchoolAssignmentsRoute
  SchoolAttendanceRoute: typeof SchoolAttendanceRoute
  SchoolCalendarRoute: typeof SchoolCalendarRoute
  SchoolGroupsRoute: typeof SchoolGroupsRoute
  SchoolMessagesRoute: typeof SchoolMessagesRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolAccountRoute: SchoolAccountRoute,
  SchoolApprovalsRoute: SchoolApprovalsRoute,
  SchoolAssignmentsRoute: SchoolAssignmentsRoute,
  SchoolAttendanceRoute: SchoolAttendanceRoute,
  SchoolCalendarRoute: SchoolCalendarRoute,
  SchoolGroupsRoute: SchoolGroupsRoute,
  SchoolMessagesRoute: SchoolMessagesRoute,
  SchoolIndexRoute: SchoolIndexRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SchoolRoute: SchoolRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
